major cleanup

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -10,33 +10,31 @@ set -e
 echo ''
 
 info () {
-  # shellcheck disable=SC2059
-  printf "\r  [ \033[00;34m..\033[0m ] $1"
+  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
 }
 
 user () {
-  # shellcheck disable=SC2059
-  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
 }
 
 success () {
-  # shellcheck disable=SC2059
   printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
 }
 
 fail () {
-  # shellcheck disable=SC2059
   printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
   echo ''
   exit
 }
 
 setup_gitconfig () {
-  if ! [ -f git/gitconfig.symlink ]; then
+  if ! [ -f git/gitconfig.symlink ]
+  then
     info 'setup gitconfig'
 
     git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]; then
+    if [ "$(uname -s)" == "Darwin" ]
+    then
       git_credential='osxkeychain'
     fi
 
@@ -54,19 +52,29 @@ setup_gitconfig () {
 
 link_file () {
   local src=$1 dst=$2
-  # shellcheck disable=SC1007
+
   local overwrite= backup= skip=
   local action=
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]; then
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then
-      # shellcheck disable=SC2086,SC2155
+
+  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
+  then
+
+    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
+    then
+
       local currentSrc="$(readlink $dst)"
-      if [ "$currentSrc" == "$src" ]; then
+
+      if [ "$currentSrc" == "$src" ]
+      then
+
         skip=true;
+
       else
+
         user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
         [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
         read -n 1 action
+
         case "$action" in
           o )
             overwrite=true;;
@@ -83,22 +91,29 @@ link_file () {
           * )
             ;;
         esac
+
       fi
+
     fi
+
     overwrite=${overwrite:-$overwrite_all}
     backup=${backup:-$backup_all}
     skip=${skip:-$skip_all}
-    if [ "$overwrite" == "true" ]; then
+
+    if [ "$overwrite" == "true" ]
+    then
       rm -rf "$dst"
       success "removed $dst"
     fi
 
-    if [ "$backup" == "true" ]; then
+    if [ "$backup" == "true" ]
+    then
       mv "$dst" "${dst}.backup"
       success "moved $dst to ${dst}.backup"
     fi
 
-    if [ "$skip" == "true" ]; then
+    if [ "$skip" == "true" ]
+    then
       success "skipped $src"
     fi
   fi
@@ -114,8 +129,9 @@ install_dotfiles () {
   info 'installing dotfiles'
 
   local overwrite_all=false backup_all=false skip_all=false
-  # shellcheck disable=SC2044
-  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 3 -name '*.symlink'); do
+
+  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+  do
     dst="$HOME/.$(basename "${src%.*}")"
     link_file "$src" "$dst"
   done
@@ -124,11 +140,16 @@ install_dotfiles () {
 setup_gitconfig
 install_dotfiles
 
-info "installing dependencies"
-if ./bin/dot_update > /tmp/dotfiles-update 2>&1 ; then
-  success "dependencies installed"
-else
-  fail "error installing dependencies"
+# If we're on a Mac, let's install and setup homebrew.
+if [ "$(uname -s)" == "Darwin" ]
+then
+  info "installing dependencies"
+  if source bin/dot_update > /tmp/dotfiles-dot 2>&1
+  then
+    success "dependencies installed"
+  else
+    fail "error installing dependencies"
+  fi
 fi
 
 echo ''
